Treat post hook errors as fatal

diff --git a/mkinitcpio b/mkinitcpio
--- a/mkinitcpio
+++ b/mkinitcpio
@@ -530,7 +530,10 @@ run_post_hooks() {
             KERNELVERSION="$KERNELVERSION" "$hook" "${args[@]}"
             status=$?
 
-            (( status )) && warning "'%s' failed with exit code %d" "$hook" "$status"
+            if (( status )); then
+                error "'%s' failed with exit code %d" "$hook" "$status"
+                return 1
+            fi
         done
     done
 
@@ -824,7 +827,7 @@ if [[ -n "$_optuki" && -n "$_optgenimg" ]]; then
 fi
 
 if (( ${#_generated[*]} )); then
-    run_post_hooks "${_generated[@]}"
+    run_post_hooks "${_generated[@]}" || (( ++_builderrors ))
 fi
 
 cleanup $(( !!_builderrors ))
